export const GETTRAVELGOODS='get_travel_goods'
export const GETTIMERSHOPS='get_time_shops'
export const GETHOTWORDS='get_hot_words'
export const GETCONTENTLIST='get_content_list'
export const GETSEARCHKEY='get_search_key'